routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sendCorn', 'BackupMySqlController@sendCorn');
Route::get('/', 'WebsiteController@index');

Route::post('/login', 'Auth\LoginController@login');

Auth::routes();

//Admin Route
Route::group(['prefix' => 'taskman', 'middleware' => 'auth'], function () {
    Route::get('profile', 'Admin\DashboardController@profile')->name('profile');
    Route::post('profile-update', 'Admin\DashboardController@updateProfile')->name('profile-update');
    Route::post('update-password', 'Admin\DashboardController@updatePassword')->name('update-password');
    Route::post('users/registerFcmToken', 'Admin\DashboardController@registerFcmToken');

    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    Route::get('media/image/{id}/delete', 'Admin\DashboardController@taskImageDelete');


    Route::get('work-list', 'Admin\WorkController@workList');
    Route::get('work/create/{task_id}', 'Admin\WorkController@create');
    Route::resource('work', 'Admin\WorkController');
    Route::post('work/sortable', 'Admin\WorkController@sortable');
    // review
    Route::resource('review', 'Admin\ReviewController');
    Route::post('review/update/{id}', 'Admin\ReviewController@update');

    //Late report
    Route::get('emp-late-report/list', 'Admin\LateReportController@empReportList')->name('emp.list');
    Route::get('emp-monthly-late-report', 'Admin\LateReportController@empMonthlyReportList')->name('emp-late-report.monthly');
    //Leave Application
    Route::resource('application', 'Admin\LeaveApplicationController');
    Route::get('get-leave-template/{id}', 'Admin\LeaveTemplateController@show');

    Route::group(['middleware' => 'management'], function () {
        Route::resource('user', 'Admin\UserController');
        Route::post('update-password/{id}', 'Admin\UserController@updatePassword')->name('user.update-password');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::post('user/reset-password/{id}', 'Admin\UserController@resetPassword');
        Route::post('user/reset-email/{id}', 'Admin\UserController@resetEmail');

        Route::resource('project', 'Admin\ProjectController');
        Route::post('user/project', 'Admin\ProjectController@sortable');

        Route::resource('task', 'Admin\TaskController');
        Route::post('task/sortable', 'Admin\TaskController@sortable');
        //ratting
        Route::get('ratting-report', 'Admin\RattingController@report');
        Route::resource('rattings', 'Admin\RattingController');
        //Late report
        Route::get('late-report/list', 'Admin\LateReportController@reportList')->name('late_report.list');
        Route::get('monthly-late-report', 'Admin\LateReportController@monthlyReportList')->name('late-report.monthly');
        Route::get('late-report/filter', 'Admin\LateReportController@filter');
        Route::resource('late-report', 'Admin\LateReportController');

        //Leave
        Route::post('/leave/update', 'Admin\LeaveController@leaveUpdate');
        Route::get('/yearly-leave-report', 'Admin\LeaveController@yearlyLeaveReport');
        Route::resource('leave', 'Admin\LeaveController');

        //Application
        Route::get('casualToSick/{id}', 'Admin\LeaveApplicationController@casualToSick');
        Route::get('sickToCasual/{id}', 'Admin\LeaveApplicationController@sickToCasual');

        Route::get('emp-application', 'Admin\LeaveApplicationController@empApplication')->name('emp.application');
        Route::get('/application/approve/{id}', 'Admin\LeaveApplicationController@applicationApprove');
        Route::get('/application/reject/{id}', 'Admin\LeaveApplicationController@applicationReject');
        //Route::resource('application', 'Admin\LeaveApplicationController');
        Route::resource('leave-template', 'Admin\LeaveTemplateController');
        Route::resource('db-backup', 'Admin\BackupController');


        Route::resource('emp-note', 'Admin\EmployeeNoteController');

        //Salary Report
        Route::get('/salary', 'Admin\SalaryController@index');
        Route::get('/year-end-salary', 'Admin\SalaryController@yearEnd');


        //Questionnaire
        Route::resource('/exam', 'Admin\ExamController');
        Route::get('/exam/questions/{exam_id}', 'Admin\ExamController@showQuestions')->name('exam.questions');
        Route::get('/exam/examine/{exam_id}', 'Admin\ExamController@showExamine')->name('exam.show-examine'); // Show Examine List along with Exam ID
        Route::post('/exam/change-activity/{id}', 'Admin\ExamController@changeActivity')->name('exam.change-activity');
        Route::resource('/question', 'Admin\ExamQuestionController');
        Route::post('/question/delete-image/{question}', 'Admin\ExamQuestionController@deleteImage');

        //Admin
        Route::resource('/applicant', 'Admin\ApplicantController');
        Route::get('/applicant/remark_show/{id}', 'Admin\ApplicantController@remark');

        // Exam Answers
        Route::get('/exam/answer/{applicant_id}', 'Admin\ExamAnswerController@showAnswers')->name('exam-answer.show');

    });

});

// This is a test route
Route::get('/interview-email', function () {
    $applicant = \App\Models\Applicant::first();
    return view('admin.exam.email', compact('applicant'));
});
// End of test route

Route::get('/interview-exam/{exam_slug}', 'Admin\ApplicantAnswerController@show')->name('interview-exam.show');
Route::post('/interview-exam/submit/{exam_id}', 'Admin\ApplicantAnswerController@submitAnswer')->name('interview-exam.submit');

app/Models/Ratting.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Ratting extends Model
{
//    protected $table = 'rattings';
    protected $guarded = ['id'];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function details()
    {
        return $this->hasMany(RattingDetail::class);
    }
}

app/Http/Controllers/Admin/RattingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Ratting;
use App\Models\RattingDetail;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;
use Validator;
use Auth;

class RattingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = $request->all();

        $rattings = Ratting::with(['details']);
        if ($request->input('user_id')) {
            $rattings = $rattings->whereHas('details', function ($query) use ($request) {
                $query->where('user_id', $request->user_id);
            });
        }
        if ($request->input('ratting')) {
            $rattings = $rattings->whereHas('details', function ($query) use ($request) {
                $query->where('ratting', $request->ratting);
            });
        }
        if ($request->input('date')) {
            $rattings->where('date', $request->date);
        }

        $rattings = $rattings->get();


//        $query = Ratting::with(['details']);
//        if (!empty($data['date'])) {
//            $query->where('date', $data['date']);
//        }
//        if (!empty($data['user_id'])) {
//            $query->whereHas('details', function ($q) use ($data) {
//                $q->where('user_id', $data['user_id']);
//            });
//        }
//
//        $rattings = $query->get();
//        dd($rattings);
        $employees = User::where('role', 'employee')
            ->where('status', 'active')
            ->orderBy('sort', 'ASC')
            ->get();
        return view('admin.rattings.index', compact('data', 'rattings', 'employees'));
    }

    public function report(Request $request)
    {
        $data = $request->all();

        $rattings = RattingDetail::with(['rattingMaster']);
        if ($request->input('manager_id')) {
            $rattings = $rattings->whereHas('rattingMaster', function ($query) use ($request) {
                $query->where('user_id', $request->manager_id);
            });
        }
        if (!empty($request->input('start_date')) && !empty($request->input('end_date'))) {
            $rattings = $rattings->whereHas('rattingMaster', function ($query) use ($request) {
                $query->whereBetween('date', [$request->start_date, $request->end_date]);
//                $query->where('date', $request->date);
            });
        }
        if ($request->input('user_id')) {
            $rattings->where('user_id', $request->user_id);
        }
        if ($request->input('ratting')) {
            $rattings->where('ratting', $request->ratting);
        }

        $rattings = $rattings->get();
//dd($rattings);
        $employees = User::where('role', 'employee')
            ->where('status', 'active')
            ->orderBy('sort', 'ASC')
            ->get();
        $managers = User::where('role', 'management')
            ->where('status', 'active')
            ->orderBy('sort', 'ASC')
            ->get();
        return view('admin.rattings.report', compact('data', 'rattings', 'employees', 'managers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = User::where('role', 'employee')
            ->where('status', 'active')
            ->orderBy('sort', 'ASC')
            ->get();
        return view('admin.rattings.create', compact('employees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $validator = Validator::make($request, [
//            'date' => 'required|date',
//        ]);
//        if ($validator->fails()) {
//            return redirect()->back()
//                ->withErrors($validator)
//                ->withInput();
//        }

        $input = $request->except('_token');

        $obj = new Ratting();
        $obj->user_id = Auth::user()->id;
        $obj->date = $request->date;
        if ($obj->save()) {
            if (!empty($input['rattings'])) {
                foreach ($input['rattings'] as $ratting) {
                    if (isset($ratting["employee_id"])) {
                        $obj->details()->create([
                            'user_id' => $ratting["employee_id"],
                            'ratting' => $ratting["ratting"],
                            'comment' => $ratting["comment"],
                        ]);
                    }
                }
            }
        }

        return redirect(route('rattings.index'))->with('success', 'Rattings Save Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        $reviews = Review::where('task_id', $id)->orderBy('date', 'DESC')->get();
        $upReview = Review::where('task_id', $id)->where('date', date('Y-m-d'))->first();
        return view('admin.rattings.view', compact('task', 'reviews', 'upReview'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ratting = Ratting::findOrFail($id);
        $employees = User::where('role', 'employee')
            ->where('status', 'active')
            ->orderBy('sort', 'ASC')
            ->get();
        return view('admin.rattings.edit', compact('ratting', 'employees'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

//        $validator = Validator::make($request, [
//            'date' => 'required|date',
//        ]);
//        if ($validator->fails()) {
//            return redirect()->back()
//                ->withErrors($validator)
//                ->withInput();
//        }

        $input = $request->except('_token');

        $obj = Ratting::findOrFail($id);
        $obj->date = $request->date;
        if ($obj->update()) {
            if (!empty($input['rattings'])) {
                $data = [];
                $row11 = RattingDetail::where('ratting_id', $obj->id)->get();
                foreach ($row11 as $data12) {
                    $array_id[] = $data12->id;
                }
                foreach ($input['rattings'] as $ratting) {
                    if (!empty($ratting["employee_id"])) {
                        $detail_id[] = isset($ratting["detail_id"]) && !empty($ratting["detail_id"] ? $ratting["detail_id"] : '');
                    }
                }
                if (!empty($array_id) && $detail_id) {
                    $remove_data = array_diff($array_id, $detail_id);
                    RattingDetail::whereIn('id', $remove_data)->delete();
                }
                foreach ($input['rattings'] as $ratting) {
                    if (!empty($ratting["employee_id"])) {
                        $data = array(
                            'ratting_id' => $obj->id,
                            'user_id' => $ratting["employee_id"],
                            'ratting' => $ratting["ratting"],
                            'comment' => $ratting["comment"],
                        );
                        $row = RattingDetail::find($ratting["detail_id"]);
                        if (!empty($row)) {
                            RattingDetail::where('id', $ratting["detail_id"])->update($data);
                        } else {
                            RattingDetail::insert($data);
                        }
                    }

                }

//                    if (isset($ratting["employee_id"])) {
//                        $obj->details()->create(
////                            ['id' => $ratting["detail_id"],],
//                            [
//                            'user_id' => $ratting["employee_id"],
//                            'ratting' => $ratting["ratting"],
//                            'comment' => $ratting["comment"],
//                        ]);
//                    }
            }
        }

        return redirect(route('rattings.index'))->with('success', 'Ratting Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public
    function destroy($id)
    {
        $obj = Ratting::findOrFail($id);
        $obj->details()->delete();
        $obj->delete();
        return redirect()->back()->with('error', 'Ratting Delete Successfully');
    }

}

resources/views/admin/rattings/edit.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Task | {!! $ratting->name !!} | Edit
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Task Create</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('task.index') !!}">Tasks</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10 col-sm-8">
                                <h4 class="card-title">Task Edit</h4>
                            </div>
                            <div class="col-md-2 col-sm-4 text-right">
                                <a href="{!! route('task.index') !!}" class="btn btn-success"><i
                                        class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('rattings.update', $ratting->id)!!}" novalidate
                              enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <h5>Date<span class="text-danger">*</span></h5>
                                        <div class="input-group">
                                            <input type="text"
                                                   class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }} datepicker-autoclose"
                                                   value="{!! $ratting->date !!}" required
                                                   data-validation-required-message="This field is required"
                                                   name="date" placeholder="Date">
                                            <div class="input-group-append">
                                                <span class="input-group-text"><i class="icon-calender"></i></span>
                                            </div>
                                            @if ($errors->has('date'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('date') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-lg-12 col-md-12 col-xs-12">
                                    <div class="table-responsive">
                                        <table id="row_create_call"
                                               class="table table-striped table-hover table-bordered display"
                                               style="width:100%">
                                            <thead>
                                            <tr>
                                                <th>Employee</th>
                                                <th>Ratting</th>
                                                <th>Commnets</th>
                                            </tr>
                                            </thead>
                                            <tbody id="tablecontents">
                                            <?php
                                            // $item_value_ids = json_decode($tailor->sell_line_note);
                                            $itemValKey = array();
                                            $itemValProperty = array();
                                            foreach ($ratting->details as $valKey => $value_property) {
                                                $itemValKey[] = $value_property->user_id;
                                                $itemValProperty[$value_property->user_id] = $value_property;
                                            }

                                            ?>
                                            @foreach($employees as $key=> $employee)
                                                <?php
                                                if (in_array($employee->id, $itemValKey)) {
                                                    $at_name = $itemValProperty[$employee->id];
                                                } else {
                                                    $at_name = "";
                                                };
                                                ?>
                                                <tr>
                                                    <td>
                                                        <input value="{{  isset($at_name->id) ? $at_name->id : "" }}"
                                                               type="hidden"
                                                               name="rattings[{{$key}}][detail_id]">

                                                        <label for="employee_id_{{$key}}">
                                                            <input
                                                                {{ isset($at_name->user_id) && $at_name->user_id ==$employee->id ? "checked" : "" }} value="{{ $employee->id }}"
                                                                id="employee_id_{{$key}}"
                                                                type="checkbox"
                                                                name="rattings[{{$key}}][employee_id]"> {{ $employee->name }}

                                                        </label>
                                                    </td>
                                                    <td>
                                                        <div class="controls">
                                                            <select
                                                                class="form-control{{ $errors->has('ratting') ? ' is-invalid' : '' }}"
                                                                name="rattings[{{$key}}][ratting]"
                                                                data-validation-required-message="This field is required">
                                                                @for ($star = 1; $star <= 10; $star++)
                                                                    <option
                                                                        {{ isset($at_name->ratting) && $at_name->ratting == $star ? "selected" : "" }} value="{{ $star }}"> {{ $star }}
                                                                        *
                                                                    </option>
                                                                @endfor
                                                            </select>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="controls">
                                                        <textarea name="rattings[{{$key}}][comment]"
                                                                  class="form-control{{ $errors->has('comment') ? ' is-invalid' : '' }}">{!! old('note') !!}{!! isset($at_name->comment) ? $at_name->comment : "" !!}</textarea>
                                                            @if ($errors->has('note'))
                                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('comment') }}</strong>
                                                </span>
                                                            @endif
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Update</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection

@section('page_js')
@endsection